# Action's main info
name: "Packj NPM Registry Firewall Setup"
description: 'Packj NPM Firewall blocks installation of vulnerable, abandonded, typo-squatted, and ESLint-/Solarwinds-like malicious open-source dependencies'

# Action's author name
author: "Ossillate, Inc."

# Action's branding data for GitHub Marketplace
branding:
  icon: "package" # icon name from Feather open source icons pack
  color: "orange"

inputs:
  PACKJ_FIREWALL_TOKEN:
    description: Your Packj Firewall service token
    required: true
  NODE_VERSION:
    description:
    default: node16
  REGISTRY_URL:
    description: URL to NPM registry (NOTE: no trailing slash)
    default: https://npmjs.packj.dev
    
runs:
  steps:
    - name: Setup node and configure Packj Firewall
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        always-auth: true
        registry-url: ${{ inputs.REGISTRY_URL }}
      run: |
        npm ci
        echo "Setting NPM package registry to ${{ inputs.REGISTRY_URL }}"
        npm config set ${{ inputs.REGISTRY_URL }}/:_authToken  "${{ github.repository }}:${{ github.run_id }}:${{ github.run_number }}:${{ github.sha }}:${{ inputs.PACKJ_FIREWALL_TOKEN }}" 
        npm test
