# Action's main info
name: "Packj NPM Registry Firewall Setup"
description: 'Packj NPM Firewall blocks installation of vulnerable, abandonded, typo-squatted, and ESLint-/Solarwinds-like malicious open-source dependencies'

# Action's author name
author: "Ossillate, Inc."

# Action's branding data for GitHub Marketplace
branding:
  icon: "package" # icon name from Feather open source icons pack
  color: "orange"

inputs:
  PACKJ_FIREWALL_TOKEN:
    description: Your Packj Firewall service token
    required: true
  NODE_VERSION:
    description: Node version to use
    required: false
    default: '16'
  REGISTRY_URL:
    description: URL to NPM registry (no trailing slash)
    required: false
    default: 'https://npmjs.packj.dev/-'
    
runs:
  using: "composite"
  
  steps:
    - name: Generate Auth token
      shell: bash
      run: |
        echo "Setting NPM package registry to ${{ inputs.REGISTRY_URL }}"
        
        # Server URL
        echo "SERVER_URL<<EOF" >> $GITHUB_ENV
        echo "${{ github.server_url }}" | base64 -w0 >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        # Repository ID
        echo "REPO_ID<<EOF" >> $GITHUB_ENV
        echo "${{ github.repository }}" | base64 -w0 >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        # Workflow details
        echo "WORKFLOW_DETAILS<<EOF" >> $GITHUB_ENV
        echo "${{ github.run_id }}:${{ github.run_number }}:${{ github.sha }}" | base64 -w0 >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        always-auth: true
        registry-url: ${{ inputs.REGISTRY_URL }}
      env:
        NODE_AUTH_TOKEN: ${{ env.SERVER_URL }}-${{ env.REPO_ID }}-${{ env.WORKFLOW_DETAILS }}-${{ inputs.PACKJ_FIREWALL_TOKEN }}
